bashvirt: prevent snapshot changes when external snaps are detected
Added detection of the external snapshots and prevent use of snapshot
functions in such a case to save user from invalid changes.

External snapshots have to be used e.g. in case of VM with UEFI.
But external snaphots are not managed by virsh so simply as internal
snapshots. Probably everyone will find own best way how to deal with
them (google it). One of the newest blogs about is:

    https://fabianlee.org/2021/01/10/kvm-creating-and-reverting-libvirt-external-snapshots/

It's more or less what I am doing in my setup.

diff --git a/bash_libs/bashvirt b/bash_libs/bashvirt
--- a/bash_libs/bashvirt
+++ b/bash_libs/bashvirt
@@ -26,6 +26,19 @@ virt_check() {
   return 1
 }
 
+_virt_external_snap_check() {
+  #
+  # Check whether the external snapshots are present for particular domain.
+  #
+  virt_check "$1" || return 1
+  [ "$(virsh snapshot-list "$1" --external | wc -l)" -eq 3 ] || {
+    echo >&2 "Error: external snapshots detected. Cannot use functions for"
+    echo >&2 "       snapshots. You have to handle it manually."
+    return 1
+  }
+  return 0
+}
+
 virt_get_mac() {
   # Print MAC addr of virtual machine with domain name $1
   virt_check "$1" || return 1
@@ -178,6 +191,7 @@ virt_snap() {
   fi
 
   virt_check "$1" || return 1
+  _virt_external_snap_check "$1" || return 1
   virsh snapshot-list "$1" | grep -q "[[:space:]]$2[[:space:]]"
   if [ $? -eq 0 ]; then
     echo >&2 "Error: snapshot already exists."
@@ -198,6 +212,7 @@ virt_snap_update() {
     return 1
   fi
   virt_check "$1" || return 1
+  _virt_external_snap_check "$1" || return 1
 
   local snap
 
@@ -222,6 +237,7 @@ virt_snap_reload() {
   # started.
   #
   virt_check "$1" || return 1
+  _virt_external_snap_check "$1" || return 1
   virsh domstate "$1" | grep -q "shut off" || virsh destroy "$1"
   virsh snapshot-revert "$1" --current
   [ "$2" == "-s" ] && virsh start "$1"
